/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EmployersRouteImport } from './routes/employers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RegisterPhysicianRouteImport } from './routes/register.physician'
import { Route as RegisterEmployerRouteImport } from './routes/register.employer'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminFaqRouteImport } from './routes/admin.faq'
import { Route as AdminEnterpriseRouteImport } from './routes/admin.enterprise'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminAssessmentsRouteImport } from './routes/admin.assessments'
import { Route as AuthenticatedDashboardPhysicianRouteImport } from './routes/_authenticated/dashboard.physician'
import { Route as AuthenticatedDashboardEmployerRouteImport } from './routes/_authenticated/dashboard.employer'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersRoute = EmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RegisterPhysicianRoute = RegisterPhysicianRouteImport.update({
  id: '/register/physician',
  path: '/register/physician',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterEmployerRoute = RegisterEmployerRouteImport.update({
  id: '/register/employer',
  path: '/register/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnterpriseRoute = AdminEnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssessmentsRoute = AdminAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedDashboardPhysicianRoute =
  AuthenticatedDashboardPhysicianRouteImport.update({
    id: '/dashboard/physician',
    path: '/dashboard/physician',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardEmployerRoute =
  AuthenticatedDashboardEmployerRouteImport.update({
    id: '/dashboard/employer',
    path: '/dashboard/employer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/enterprise': typeof AdminEnterpriseRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/register/employer': typeof RegisterEmployerRoute
  '/register/physician': typeof RegisterPhysicianRoute
  '/admin/': typeof AdminIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/dashboard/employer': typeof AuthenticatedDashboardEmployerRoute
  '/dashboard/physician': typeof AuthenticatedDashboardPhysicianRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/enterprise': typeof AdminEnterpriseRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/register/employer': typeof RegisterEmployerRoute
  '/register/physician': typeof RegisterPhysicianRoute
  '/admin': typeof AdminIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/register': typeof RegisterIndexRoute
  '/dashboard/employer': typeof AuthenticatedDashboardEmployerRoute
  '/dashboard/physician': typeof AuthenticatedDashboardPhysicianRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/enterprise': typeof AdminEnterpriseRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/register/employer': typeof RegisterEmployerRoute
  '/register/physician': typeof RegisterPhysicianRoute
  '/admin/': typeof AdminIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/_authenticated/dashboard/employer': typeof AuthenticatedDashboardEmployerRoute
  '/_authenticated/dashboard/physician': typeof AuthenticatedDashboardPhysicianRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/assessment'
    | '/contact'
    | '/employers'
    | '/faq'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/testimonials'
    | '/admin/assessments'
    | '/admin/contacts'
    | '/admin/enterprise'
    | '/admin/faq'
    | '/admin/jobs'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/revenue'
    | '/admin/testimonials'
    | '/admin/users'
    | '/jobs/$jobId'
    | '/register/employer'
    | '/register/physician'
    | '/admin/'
    | '/jobs/'
    | '/register/'
    | '/dashboard/employer'
    | '/dashboard/physician'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assessment'
    | '/contact'
    | '/employers'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/testimonials'
    | '/admin/assessments'
    | '/admin/contacts'
    | '/admin/enterprise'
    | '/admin/faq'
    | '/admin/jobs'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/revenue'
    | '/admin/testimonials'
    | '/admin/users'
    | '/jobs/$jobId'
    | '/register/employer'
    | '/register/physician'
    | '/admin'
    | '/jobs'
    | '/register'
    | '/dashboard/employer'
    | '/dashboard/physician'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/assessment'
    | '/contact'
    | '/employers'
    | '/faq'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/testimonials'
    | '/admin/assessments'
    | '/admin/contacts'
    | '/admin/enterprise'
    | '/admin/faq'
    | '/admin/jobs'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/revenue'
    | '/admin/testimonials'
    | '/admin/users'
    | '/jobs/$jobId'
    | '/register/employer'
    | '/register/physician'
    | '/admin/'
    | '/jobs/'
    | '/register/'
    | '/_authenticated/dashboard/employer'
    | '/_authenticated/dashboard/physician'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssessmentRoute: typeof AssessmentRoute
  ContactRoute: typeof ContactRoute
  EmployersRoute: typeof EmployersRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TestimonialsRoute: typeof TestimonialsRoute
  RegisterEmployerRoute: typeof RegisterEmployerRoute
  RegisterPhysicianRoute: typeof RegisterPhysicianRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers': {
      id: '/employers'
      path: '/employers'
      fullPath: '/employers'
      preLoaderRoute: typeof EmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/register/physician': {
      id: '/register/physician'
      path: '/register/physician'
      fullPath: '/register/physician'
      preLoaderRoute: typeof RegisterPhysicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/employer': {
      id: '/register/employer'
      path: '/register/employer'
      fullPath: '/register/employer'
      preLoaderRoute: typeof RegisterEmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enterprise': {
      id: '/admin/enterprise'
      path: '/enterprise'
      fullPath: '/admin/enterprise'
      preLoaderRoute: typeof AdminEnterpriseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assessments': {
      id: '/admin/assessments'
      path: '/assessments'
      fullPath: '/admin/assessments'
      preLoaderRoute: typeof AdminAssessmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/dashboard/physician': {
      id: '/_authenticated/dashboard/physician'
      path: '/dashboard/physician'
      fullPath: '/dashboard/physician'
      preLoaderRoute: typeof AuthenticatedDashboardPhysicianRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/employer': {
      id: '/_authenticated/dashboard/employer'
      path: '/dashboard/employer'
      fullPath: '/dashboard/employer'
      preLoaderRoute: typeof AuthenticatedDashboardEmployerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardEmployerRoute: typeof AuthenticatedDashboardEmployerRoute
  AuthenticatedDashboardPhysicianRoute: typeof AuthenticatedDashboardPhysicianRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardEmployerRoute: AuthenticatedDashboardEmployerRoute,
  AuthenticatedDashboardPhysicianRoute: AuthenticatedDashboardPhysicianRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminAssessmentsRoute: typeof AdminAssessmentsRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminEnterpriseRoute: typeof AdminEnterpriseRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssessmentsRoute: AdminAssessmentsRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminEnterpriseRoute: AdminEnterpriseRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AssessmentRoute: AssessmentRoute,
  ContactRoute: ContactRoute,
  EmployersRoute: EmployersRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TestimonialsRoute: TestimonialsRoute,
  RegisterEmployerRoute: RegisterEmployerRoute,
  RegisterPhysicianRoute: RegisterPhysicianRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
