# Generated by Django 6.0.5 on 2026-05-15 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("anatomical_pathology", "Anatomical Pathology"),
                            ("anesthesiology", "Anesthesiology"),
                            ("cardiac_surgery", "Cardiac Surgery"),
                            ("dermatology", "Dermatology"),
                            ("diagnostic_radiology", "Diagnostic Radiology"),
                            ("emergency_medicine", "Emergency Medicine"),
                            ("family_medicine", "Family Medicine"),
                            ("internal_medicine", "Internal Medicine"),
                            ("general_surgery", "General Surgery"),
                            ("neurology", "Neurology"),
                            ("obstetrics_gynecology", "Obstetrics and Gynecology"),
                            ("pediatrics", "Pediatrics"),
                            ("psychiatry", "Psychiatry"),
                            ("urology", "Urology"),
                            ("vascular_surgery", "Vascular Surgery"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "sub_specialty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cardiology", "Cardiology"),
                            ("critical_care", "Critical Care Medicine"),
                            ("gastroenterology", "Gastroenterology"),
                            ("geriatric_medicine", "Geriatric Medicine"),
                            ("hematology", "Hematology"),
                            ("infectious_diseases", "Infectious Diseases"),
                            ("medical_oncology", "Medical Oncology"),
                            ("nephrology", "Nephrology"),
                            ("pain_medicine", "Pain Medicine"),
                            ("palliative_medicine", "Palliative Medicine"),
                            ("respirology", "Respirology"),
                            ("rheumatology", "Rheumatology"),
                            ("thoracic_surgery", "Thoracic Surgery"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("AB", "Alberta"),
                            ("BC", "British Columbia"),
                            ("MB", "Manitoba"),
                            ("NB", "New Brunswick"),
                            ("NL", "Newfoundland and Labrador"),
                            ("NT", "Northwest Territories"),
                            ("NS", "Nova Scotia"),
                            ("NU", "Nunavut"),
                            ("ON", "Ontario"),
                            ("PE", "Prince Edward Island"),
                            ("QC", "Quebec"),
                            ("SK", "Saskatchewan"),
                            ("YT", "Yukon"),
                        ],
                        max_length=2,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("location_display", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField()),
                ("qualifications", models.TextField()),
                ("compensation", models.TextField(blank=True)),
                ("benefits", models.TextField(blank=True)),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("contact_person", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("locum", "Locum"),
                            ("contract", "Contract"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="accounts.employerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover_letter", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("shortlisted", "Shortlisted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
                (
                    "physician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="accounts.physicianprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
                "unique_together": {("job", "physician")},
            },
        ),
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="jobs.job",
                    ),
                ),
                (
                    "physician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_jobs",
                        to="accounts.physicianprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-saved_at"],
                "unique_together": {("physician", "job")},
            },
        ),
    ]
