# Generated by Django 6.0.5 on 2026-05-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_user_type"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["is_active", "is_approved"], name="job_active_approved_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["specialty"], name="job_specialty_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["province"], name="job_province_idx"),
        ),
    ]
