# Generated by Django 5.2.7 on 2026-05-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_admin_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="compensation_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("salary", "Salary"),
                    ("fee_for_service", "Fee for Service"),
                    ("alternative_payment", "Alternative Payment Plan"),
                    ("blended", "Blended Model"),
                    ("contract_rate", "Contract Rate"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="practice_setting",
            field=models.CharField(
                blank=True,
                choices=[
                    ("urban", "Urban"),
                    ("suburban", "Suburban"),
                    ("rural", "Rural"),
                    ("northern_remote", "Northern / Remote"),
                    ("academic_teaching", "Academic / Teaching"),
                    ("community_hospital", "Community Hospital"),
                    ("private_clinic", "Private Clinic"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_display",
            field=models.CharField(
                blank=True,
                help_text="e.g. $280K - $320K/yr (shown on job cards)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum annual salary in CAD",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum annual salary in CAD",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("locum", "Locum"),
                    ("contract", "Contract"),
                    ("fellowship", "Fellowship"),
                ],
                default="full_time",
                max_length=20,
            ),
        ),
    ]
