# Generated by Django 5.2.7 on 2026-05-15 18:59

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job_compensation_model_job_practice_setting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="relocation_assistance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="remote_option",
            field=models.BooleanField(
                default=False, help_text="Position allows remote/telemedicine work"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="required_experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new_grad", "New Graduate"),
                    ("1_3_years", "1–3 Years"),
                    ("3_5_years", "3–5 Years"),
                    ("5_10_years", "5–10 Years"),
                    ("10_plus", "10+ Years"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="requirements",
            field=models.TextField(
                blank=True,
                help_text="Required licences, certifications, years of experience etc.",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="responsibilities",
            field=models.TextField(
                blank=True, help_text="Day-to-day duties and responsibilities"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="availability_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="employer_notes",
            field=models.TextField(
                blank=True, help_text="Internal notes visible only to the employer"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="resume",
            field=models.FileField(
                blank=True,
                help_text="CV/resume submitted with this application",
                null=True,
                upload_to=jobs.models.application_resume_path,
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="willing_to_relocate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="years_experience",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_display",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("reviewed", "Reviewed"),
                    ("shortlisted", "Shortlisted"),
                    ("interview", "Interview"),
                    ("offered", "Offered"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
