# Generated by Django 5.2.7 on 2026-05-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_user_type"),
        ("jobs", "0005_job_is_featured_job_relocation_assistance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="required_experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new_grad", "New Graduate"),
                    ("1_3_years", "1-3 Years"),
                    ("3_5_years", "3-5 Years"),
                    ("5_10_years", "5-10 Years"),
                    ("10_plus", "10+ Years"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["employer", "is_active"], name="job_employer_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["physician", "status"], name="app_physician_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(fields=["job", "status"], name="app_job_status_idx"),
        ),
    ]
