# Generated by Django 5.2.7 on 2026-05-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_user_type"),
        ("jobs", "0006_alter_job_required_experience_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["job_type", "province"], name="job_type_province_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["-created_at"], name="job_created_at_idx"),
        ),
    ]
