# Generated by Django 5.2.7 on 2026-05-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_job_job_type_province_idx_job_job_created_at_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("reviewed", "Reviewed"),
                    ("shortlisted", "Shortlisted"),
                    ("interview", "Interview"),
                    ("offered", "Offered"),
                    ("accepted", "Accepted"),
                    ("offer_declined", "Offer Declined"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
