# Generated by Django 6.0.5 on 2026-05-15 03:05

import assessments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CareerAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("specialty", models.CharField(max_length=100)),
                ("sub_specialty", models.CharField(blank=True, max_length=100)),
                ("current_location", models.CharField(max_length=255)),
                ("desired_province_in_canada", models.CharField(max_length=100)),
                ("years_of_experience", models.PositiveIntegerField()),
                (
                    "licensure_status",
                    models.CharField(
                        choices=[
                            ("licensed_canada", "Licensed in Canada"),
                            ("licensed_other", "Licensed in Another Country"),
                            ("in_process", "In Process"),
                            ("not_yet", "Not Yet Licensed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "work_eligibility",
                    models.CharField(
                        choices=[
                            ("citizen", "Canadian Citizen"),
                            ("pr", "Permanent Resident"),
                            ("work_permit", "Work Permit Holder"),
                            ("need_sponsorship", "Need Sponsorship"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=assessments.models.assessment_resume_path,
                    ),
                ),
                ("career_goals", models.TextField()),
                ("relocation_support_needed", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_reviewed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
