# Generated by Django 5.2.7 on 2026-05-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerassessment",
            name="additional_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="careerassessment",
            name="admin_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="careerassessment",
            name="availability_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="careerassessment",
            name="preferred_job_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="careerassessment",
            name="preferred_practice_setting",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="careerassessment",
            name="salary_expectation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="careerassessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("under_review", "Under Review"),
                    ("contacted", "Contacted"),
                    ("in_progress", "In Progress"),
                    ("placed", "Placed"),
                    ("closed", "Closed"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="careerassessment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
