# Generated by Django 5.2.7 on 2026-05-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("job", "New Job"),
                    ("physician", "New Physician"),
                    ("employer", "New Employer"),
                    ("assessment", "New Assessment"),
                    ("contact", "New Contact"),
                    ("enterprise", "Enterprise Request"),
                ],
                max_length=20,
            ),
        ),
    ]
