# Generated by Django 6.0.5 on 2026-05-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_active_jobs", models.PositiveIntegerField(default=0)),
                ("new_opportunities", models.PositiveIntegerField(default=0)),
                ("total_active_candidates", models.PositiveIntegerField(default=0)),
                ("new_candidates", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform Stats",
                "verbose_name_plural": "Platform Stats",
            },
        ),
    ]
