# Generated by Django 6.0.5 on 2026-05-15 03:05

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("physician", "Physician"), ("employer", "Employer")],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.CreateModel(
            name="EmployerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "company_type",
                    models.CharField(
                        choices=[("recruiter", "Recruiter"), ("employer", "Employer")],
                        max_length=20,
                    ),
                ),
                ("company_phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                (
                    "contact_person_first_name",
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    "contact_person_last_name",
                    models.CharField(blank=True, max_length=150),
                ),
                ("website", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhysicianProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("anatomical_pathology", "Anatomical Pathology"),
                            ("anesthesiology", "Anesthesiology"),
                            ("cardiac_surgery", "Cardiac Surgery"),
                            ("dermatology", "Dermatology"),
                            ("diagnostic_radiology", "Diagnostic Radiology"),
                            ("emergency_medicine", "Emergency Medicine"),
                            ("family_medicine", "Family Medicine"),
                            ("internal_medicine", "Internal Medicine"),
                            ("general_surgery", "General Surgery"),
                            ("neurology", "Neurology"),
                            ("obstetrics_gynecology", "Obstetrics and Gynecology"),
                            ("pediatrics", "Pediatrics"),
                            ("psychiatry", "Psychiatry"),
                            ("urology", "Urology"),
                            ("vascular_surgery", "Vascular Surgery"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "sub_specialty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cardiology", "Cardiology"),
                            ("critical_care", "Critical Care Medicine"),
                            ("gastroenterology", "Gastroenterology"),
                            ("geriatric_medicine", "Geriatric Medicine"),
                            ("hematology", "Hematology"),
                            ("infectious_diseases", "Infectious Diseases"),
                            ("medical_oncology", "Medical Oncology"),
                            ("nephrology", "Nephrology"),
                            ("pain_medicine", "Pain Medicine"),
                            ("palliative_medicine", "Palliative Medicine"),
                            ("respirology", "Respirology"),
                            ("rheumatology", "Rheumatology"),
                            ("thoracic_surgery", "Thoracic Surgery"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("cpso_number", models.CharField(blank=True, max_length=20)),
                ("board_certifications", models.TextField(blank=True)),
                ("degrees", models.TextField(blank=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField(blank=True)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("work_eligibility", models.BooleanField(default=False)),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.physician_resume_path,
                    ),
                ),
                ("profile_complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="physician_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
