# Generated by Django 6.0.5 on 2026-05-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("physician", "Physician"),
                    ("employer", "Employer"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
