# Generated by Django 5.2.7 on 2026-05-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="employer_logos/"),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="province",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="country",
            field=models.CharField(blank=True, default="Canada", max_length=100),
        ),
    ]
