# Generated by Django 5.2.7 on 2026-05-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_city_province_logo_to_employer_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="physicianprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="physician_avatars/"
            ),
        ),
        migrations.AddField(
            model_name="physicianprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="physicianprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="physicianprofile",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="physicianprofile",
            name="province",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="physicianprofile",
            name="years_of_experience",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="physicianprofile",
            name="country",
            field=models.CharField(blank=True, default="Canada", max_length=100),
        ),
    ]
