from django.urls import path
from .views import (
    JobListCreateView,
    JobDetailView,
    JobCloseView,
    JobReopenView,
    JobDuplicateView,
    EmployerMyJobsView,
    EmployerAllApplicationsView,
    ApplyToJobView,
    MyApplicationsView,
    WithdrawApplicationView,
    SaveJobView,
    UnsaveJobView,
    SavedJobsListView,
    SpecialtiesListView,
    SubSpecialtiesListView,
    ProvincesListView,
    PracticeSettingsListView,
    JobApplicationsForEmployerView,
    UpdateApplicationStatusView,
    FeaturedRecruitersView,
    JobPDFView,
)

urlpatterns = [
    path('', JobListCreateView.as_view(), name='job-list-create'),
    path('my-jobs/', EmployerMyJobsView.as_view(), name='employer-my-jobs'),
    path('employer-applications/', EmployerAllApplicationsView.as_view(), name='employer-all-applications'),
    path('my-applications/', MyApplicationsView.as_view(), name='my-applications'),
    path('saved/', SavedJobsListView.as_view(), name='saved-jobs'),
    path('specialties/', SpecialtiesListView.as_view(), name='specialties'),
    path('sub-specialties/', SubSpecialtiesListView.as_view(), name='sub-specialties'),
    path('provinces/', ProvincesListView.as_view(), name='provinces'),
    path('practice-settings/', PracticeSettingsListView.as_view(), name='practice-settings'),
    path('<int:pk>/', JobDetailView.as_view(), name='job-detail'),
    path('<int:pk>/close/', JobCloseView.as_view(), name='job-close'),
    path('<int:pk>/reopen/', JobReopenView.as_view(), name='job-reopen'),
    path('<int:pk>/duplicate/', JobDuplicateView.as_view(), name='job-duplicate'),
    path('<int:pk>/apply/', ApplyToJobView.as_view(), name='apply-to-job'),
    path('<int:pk>/save/', SaveJobView.as_view(), name='save-job'),
    path('<int:pk>/unsave/', UnsaveJobView.as_view(), name='unsave-job'),
    path('applications/<int:pk>/status/', UpdateApplicationStatusView.as_view(), name='update-application-status'),
    path('applications/<int:pk>/', WithdrawApplicationView.as_view(), name='withdraw-application'),
    path('featured-recruiters/', FeaturedRecruitersView.as_view(), name='featured-recruiters'),
    path('<int:pk>/applications/', JobApplicationsForEmployerView.as_view(), name='job-applications-for-employer'),
    path('<int:pk>/pdf/', JobPDFView.as_view(), name='job-pdf'),
]
