# Generated by Django 6.0.5 on 2026-05-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_enterpriserequest_customsubscriptionplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="customsubscriptionplan",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("paid", "Paid"),
                    ("free", "Free (No Charge)"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customsubscriptionplan",
            name="stripe_payment_link_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customsubscriptionplan",
            name="stripe_payment_link_url",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customsubscriptionplan",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="customsubscriptionplan",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
