# Generated by Django 5.2.7 on 2026-05-17 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_customsubscriptionplan_payment_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="enterpriserequest",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enterpriserequest",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revoked_enterprise_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customsubscriptionplan",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("paid", "Paid"),
                    ("free", "Free (No Charge)"),
                    ("revoked", "Revoked"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="enterpriserequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("reviewing", "Reviewing"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("revoked", "Revoked"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
