# Generated by Django 5.2.7 on 2026-05-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_enterprise_request_custom_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterpriserequest",
            name="monthly_hiring_volume",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
