# Generated by Django 5.2.7 on 2026-05-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_remove_volume_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterpriserequest",
            name="revoked_reason",
            field=models.TextField(blank=True),
        ),
    ]
