# Generated by Django 6.0.5 on 2026-05-15 03:05

import testimonials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("physician_name", models.CharField(max_length=255)),
                ("specialty", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("testimonial_text", models.TextField()),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=testimonials.models.testimonial_photo_path,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
