# Generated by Django 5.2.7 on 2026-05-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="organization",
            field=models.CharField(
                blank=True,
                help_text="For employer testimonials: organization name and role",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="testimonial_type",
            field=models.CharField(
                choices=[("physician", "Physician"), ("employer", "Employer")],
                default="physician",
                max_length=20,
            ),
        ),
    ]
