# Generated by Django 5.2.7 on 2026-05-16 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("admin_job", "New Job Submitted"),
                            ("admin_physician", "New Physician Registered"),
                            ("admin_employer", "New Employer Registered"),
                            ("admin_assessment", "New Assessment Submitted"),
                            ("admin_contact", "New Contact Message"),
                            ("employer_application", "New Job Application"),
                            ("employer_job_approved", "Job Approved"),
                            ("employer_job_rejected", "Job Rejected"),
                            ("physician_app_status", "Application Status Changed"),
                            (
                                "physician_assessment_status",
                                "Assessment Status Updated",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="Frontend route to navigate to on click",
                        max_length=500,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null means admin-only notification (delivered to all staff)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
